# Generated by Django 5.1.4 on 2024-12-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
