# Generated by Django 5.1.4 on 2025-01-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_seller_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
